version: "3"
services: 
    frontend-app:
      image: frontend-app
      build: ./frontend/
      stdin_open: true
      ports:
          - '3000:3000'
      networks:
          - mern-app
    api-server: 
      image: api-server
      build: ./api/
      ports:
          - '5000:5000'
      networks:
          - mern-app
      depends_on:
          - mongo
    mongo:
      image: mongo:4.4-bionic
      ports:
          - '27017:27017'
      networks:
          - mern-app
      volumes:
          - mongo-data:/data/db
networks:
  mern-app:
      driver: bridge
volumes:
  mongo-data:
      driver: local